# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [19]:
np.empty((2,2),dtype='int32')

array([[ 1262746869, -2117160148],
       [  406929304,       32530]], dtype=int32)

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [23]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)

array([[142352912,     22016,         0],
       [        0,         0,         0]], dtype=int32)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [92]:
x= np.zeros((3,3,3))
x[:,[0,1,2],[0,1,2]]=1
# print(x)

# arr_eye = np.eye(3,3)
# # print(arr_eye)

stacked_eye=np.stack([np.eye(3,3) for _ in range(3)],axis=0)
print(stacked_eye)



[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]


Create a new array of 3*2 float numbers, filled with ones.

In [59]:
np.ones((3,2),dtype='float32')

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [63]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1])

Create a new array of 3*2 float numbers, filled with zeros.

In [64]:
np.zeros((3,2),dtype='float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [66]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0])

Create a new array of 2*5 uints, filled with 6.

In [94]:
np.full((2,5),fill_value=6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [95]:
x = np.arange(4, dtype=np.int64)
np.full_like(x,fill_value=6)

array([6, 6, 6, 6])

## From existing data

Create an array of [1, 2, 3].

In [96]:
np.array([1,2,3])

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [97]:
x = [1,2]
np.array(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [99]:
X = np.array([[1, 2], [3, 4]])
np.matrix(X)

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [3]:
x = [1, 2]
np.array(x,dtype='float')

array([1., 2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [28]:
x = np.array([30])
x.item()
#for more than 1 elem ndarray
arr= np.empty((4,),dtype='float')
arr_ls = arr.astype('float').tolist()
print(arr_ls)

[0.0, 0.0, 0.0, 0.0]


Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [33]:
x = np.array([1, 2, 3])
x_copy = x.copy()
x_pseudo_copy  = x
#id for comparing the memory address (unique py object id)
print(id(x),id(x_copy),id(x_pseudo_copy))

140251354479184 140251354672240 140251354479184


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [35]:
np.arange(2,102,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [91]:
arr_linspace = np.linspace(start=3,stop=10,endpoint=False,num=50)
arr_uniform= np.random.uniform(low=3,high=11,size=50)
##there is a difference between the uniform distribution and linear space (distribution versus ruler)
print('linear space :',arr_linspace[:5])
print('_____________________')
print('uniform distribution:',arr_uniform[:5])



linear space : [3.   3.14 3.28 3.42 3.56]
_____________________
uniform distribution: [10.09585471 10.82061904  3.43391913  5.51637347  8.10445252]


Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [79]:
np.logspace(start=3,stop=10,endpoint=True,num=50)

array([1.00000000e+03, 1.38949549e+03, 1.93069773e+03, 2.68269580e+03,
       3.72759372e+03, 5.17947468e+03, 7.19685673e+03, 1.00000000e+04,
       1.38949549e+04, 1.93069773e+04, 2.68269580e+04, 3.72759372e+04,
       5.17947468e+04, 7.19685673e+04, 1.00000000e+05, 1.38949549e+05,
       1.93069773e+05, 2.68269580e+05, 3.72759372e+05, 5.17947468e+05,
       7.19685673e+05, 1.00000000e+06, 1.38949549e+06, 1.93069773e+06,
       2.68269580e+06, 3.72759372e+06, 5.17947468e+06, 7.19685673e+06,
       1.00000000e+07, 1.38949549e+07, 1.93069773e+07, 2.68269580e+07,
       3.72759372e+07, 5.17947468e+07, 7.19685673e+07, 1.00000000e+08,
       1.38949549e+08, 1.93069773e+08, 2.68269580e+08, 3.72759372e+08,
       5.17947468e+08, 7.19685673e+08, 1.00000000e+09, 1.38949549e+09,
       1.93069773e+09, 2.68269580e+09, 3.72759372e+09, 5.17947468e+09,
       7.19685673e+09, 1.00000000e+10])

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [5]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
X.diagonal()

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [17]:
init_arr = np.zeros((4,4),dtype='int')
init_arr[[0,1,2,3],[0,1,2,3]] = np.arange(1,5)
print(init_arr)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [25]:
resarr= np.ones((3,5),dtype='int')
#tril gets lower part of diagonal
np.tril(resarr,k=-1)
#triu upper part of diagonal
# np.triu(resarr,k=1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [38]:
#natanaiil azamt dar negahe towst na daran chizi ke be aan minegari (full arange created array got zero on parts)
pre_arr = np.arange(1,13).reshape(4,3)
post_arr = np.tril(pre_arr,k=-1)
print(pre_arr)
print(post_arr)
#reshape is the most important thing in this matter

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 0  0  0]
 [ 4  0  0]
 [ 7  8  0]
 [10 11 12]]


Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [40]:
post_arr_2 = np.triu(pre_arr,k=-1)
print(post_arr_2)

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]
